version: '3.4'

volumes:
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/redis/data

services:
  webhook-tester:
    image: tarampampam/webhook-tester:local
    restart: always
    command: serve --port 8080 --log-json --storage-driver redis --pubsub-driver redis --redis-dsn redis://redis:6379/0
    ports:
      - '8080:8080/tcp' # Open <http://127.0.0.1:8080>

  redis:
    image: redis:6.0.9-alpine
    restart: always
    volumes:
      - redis-data:/data:cached
